name: charging_station
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^14.0.0
  permission_handler: ^12.0.0+1
  url_launcher: ^6.0.9
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  easy_localization: ^3.0.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/langs/
